# Generated by Django 5.0.3 on 2024-03-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeitorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_do_produto',
        ),
    ]
