# Generated by Django 5.0.3 on 2024-03-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeitorApp', '0002_rename_nome_produto_nome_do_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
