# Generated by Django 5.0.3 on 2024-03-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeitorApp', '0006_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_do_produto',
            new_name='nome_da_categoria',
        ),
    ]
