# Generated by Django 5.0.3 on 2024-03-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeitorApp', '0008_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
                ('estado', models.CharField(choices=[('RJ', 'RJ'), ('SP', 'SP'), ('MG', 'MG'), ('BA', 'BAHIA'), ('GO', 'GOIAS'), ('PR', 'PARANÁ'), ('RS', 'RS'), ('OUTRA', 'OUTRA')], max_length=6)),
            ],
        ),
    ]
